unit TestPrincipal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Principal, Vcl.StdCtrls, Winapi.Windows,
  System.Variants, Vcl.Graphics, Vcl.Dialogs, Vcl.Controls, Vcl.Forms, Winapi.Messages,
  System.Classes;

type
  // Test methods for class TForm1

  TestTForm1 = class(TTestCase)
  strict private
    Y: Double;
    X: Double;
    FForm1: TfrmPrincipal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomar;
    procedure TestSubtrair;
    procedure TestMultiplicar;
    procedure TestDividir;
  end;

implementation

procedure TestTForm1.SetUp;
begin
  FForm1 := TfrmPrincipal.Create(nil);

  Y := 10;
  X := 5;
end;

procedure TestTForm1.TearDown;
begin
  FForm1.Free;
  FForm1 := nil;
end;

procedure TestTForm1.TestSomar;
var
  ReturnValue: Double;
begin
  ReturnValue := FForm1.Somar(X, Y);
  CheckEquals((X+Y), ReturnValue);
end;

procedure TestTForm1.TestSubtrair;
var
  ReturnValue: Double;
begin
  ReturnValue := FForm1.Subtrair(X, Y);
  CheckEquals((X-Y), ReturnValue);
end;

procedure TestTForm1.TestMultiplicar;
var
  ReturnValue: Double;
begin
  ReturnValue := FForm1.Multiplicar(X, Y);
//  CheckEquals((X+Y), ReturnValue); // gerar erro
  CheckEquals((X*Y), ReturnValue);
end;

procedure TestTForm1.TestDividir;
var
  ReturnValue: Double;
begin
  ReturnValue := FForm1.Dividir(X, Y);
  CheckEquals((X/Y), ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTForm1.Suite);
end.

